### ISSUE TITLE
Appel de /secret à chaque page

### ISSUE THREAD

**Issue by Arnoid31** [Akrobate/nuitLiquide-front#1]
Mais mais mais... why ? Le token généré est disponible pour toute la durée de la session, inutile de le rafraichir à chaque fois ;) (pour info, il expire après 30 minutes d'inactivité)

**Comment by Arnoid31** [comment]
(Rq : Seulement si pas connecté)

**Comment by Akrobate** [comment]
J'ai pas obesrvé ca.... Par contre pour le moment pas de coooooooockie so chaque F5 ou acces par url a un lien genere un token.... C'est pas un bug.. Pour le moment c'est une feature transverse au développement (c'est comme le hash ;-)  )

**Comment by Akrobate** [comment]
ps je close l'issue pour le moment =)
