### ISSUE TITLE
Login/Inscription

### ISSUE THREAD

**Issue by Arnoid31** [Akrobate/nuitLiquide-front#2]
Juste pour dire, les champs login/mdp remplissent aussi les champs email/mdp pour l'inscription

**Comment by Akrobate** [comment]
Je veux bien savoir sur quoi t'as testé ca.... J'ai pas observé ca , mais effectivement dans le code il pouvait il y avoir des choses (names identiques) qui pouvaient generer des choses bizzares!! =)
j'ai fait un fix, dis moi si cela te semble correct à présent
